spring:
  application:
    name: api-gateway-service

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/auth/jwks-json

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/auth/**

            - id: like-service
              uri: http://like-service:8082
              predicates:
                - Path=/api/likes/**

            - id: comment-service
              uri: http://comment-service:8083
              predicates:
                - Path=/api/comments/**

            - id: share-service
              uri: http://share-service:8084
              predicates:
                - Path=/api/share/**

server:
  port: 8080